name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies by running `make install`
    - name: Install dependencies
      run: make install

    # Run the Flask application with a sleep to give it time to start
    - name: Run Flask application
      run: |
        make run &
        sleep 3

    # Run tests (if any), or verify that the server is up
    # You can add your own logic here to verify your app is running correctly
    - name: Verify Flask application is running
      run: |
        curl http://localhost:3000 || exit 1
